### ISSUE TITLE
Transfer repo ownership from @JetteReeg to RSdevs

### ISSUE THREAD

**Issue by JetteReeg** [RangeShifter/RangeShifter_batch#7]

**Comment by JetteReeg** [comment]
I transfered the repository to @RangeShifter/rs_developers so we have all RangeShifter repositories in one organization, but limit access via teams.

**Comment by TheoPannetier** [comment]
Thanks for this! I think this is done so I'm closing this issue, do re-open if there's still anything that need to be addressed here!

**Comment by TheoPannetier** [comment]
@JetteReeg just a note - I had to update the remotes (`origin` and `RScore`) after the ownership transfer, as they were still pointing to `JetteReeg/Rangeshifter_restruct` and `JetteReeg/RScore`, respectively.
You'll probably want to do the same! 
(`git remote -v` to check where they point, `git remote remove <name>` + `git remote add <name> <new url>` to update)
